name: ethio_commerce_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  flutter_vector_icons: ^2.0.0
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/Pattern.png
    - assets/images/Pattern2.png
    - assets/images/Paypal.png
    - assets/images/Visa.png
    - assets/images/Payoneer.png
    - assets/images/Illustration.png
    - assets/images/Illustration1.png
    - assets/images/PinLogo.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/Gallery.png
    - assets/images/Camera.png
    - assets/images/envelope.svg
    - assets/images/chat.svg
    - assets/images/equalizer.svg
    - assets/images/notification.svg
    - assets/images/cardImg.png
    - assets/images/veganL.png
    - assets/images/healthy.png
    - assets/images/cardImgBG.png
    - assets/images/greenN.png

    # - assets/fonts/
  # fonts:
  #   - family: BentonSans Book 
  #     fonts:
  #       - asset: assets/fonts/benton-sans-book.otf  

  